version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/sqlite.db:/backend/sqlite.db
    ports:
      - "3000:3000"
  nginx:
      build:
        dockerfile: ./nginx/Dockerfile
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8018:80"
